# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
import codecs

class SeleniumRobot():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10) # seconds
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def getCapp(self,studentId):
    self.driver.find_element(By.CSS_SELECTOR, "#contentItem11 > h3").click()
    self.driver.find_element(By.ID, "Stu_ID").click()
    self.driver.find_element(By.ID, "Stu_ID").send_keys(studentId)
    self.driver.find_element(By.CSS_SELECTOR, "#id____UID8 > .defaultButtonSmall > div > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".defaultButtonSmall > div > div").click()
    #sleep(0.1)
    self.driver.find_element(By.CSS_SELECTOR, "#contentItem18 > h3").click()
    self.driver.find_element(By.LINK_TEXT, "Reportes de cumplimiento").click()
    self.driver.find_element(By.LINK_TEXT, "Ing Diseño Entret Digital-Med").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(7) > .fieldlabeltext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".defaultButtonSmall > div > div").click()
    #sleep(0.1)
    file = codecs.open("./capp.html", "w", "utf−8")
    h = self.driver.page_source
    file.write(h)
    file.flush()
    self.driver.execute_script("window.history.go(-1)")
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(10) > .fieldlabeltext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".defaultButtonSmall > div > div").click()
    file = codecs.open("./infoAdd.html", "w", "utf−8")
    h = self.driver.page_source
    file.write(h)
    file.flush()
    self.driver.execute_script("window.history.go(-1)")
    self.driver.execute_script("window.history.go(-1)")
    self.driver.execute_script("window.history.go(-1)")
    self.driver.execute_script("window.history.go(-1)")

  def initCapp(self, user,id):
    self.driver.get("https://www.upb.edu.co/es/home")
    self.driver.set_window_size(960, 960)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "SIGAA").click()
    self.vars["win9549"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9549"])
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys(user)
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-login100").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys(id)
    self.driver.find_element(By.CSS_SELECTOR, ".login100-form-btn:nth-child(1)").click()
    #sleep(0.1)
    self.driver.find_element(By.CSS_SELECTOR, "#bmenu--P_FacMainMnu___UID3 span").click()
    #sleep(0.1)
    self.driver.find_element(By.CSS_SELECTOR, "#bmenu--P_FacAdvrMnu___UID6 b").click()
    #sleep(0.1)
    self.driver.find_element(By.CSS_SELECTOR, "#contentItem20 > h3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".defaultButtonSmall > div > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "#contentItem21 > h3").click()


    
